import Head from "next/head";
import Image from "next/image";
// import { createUseStyles } from "react-jss";
import styles from "../styles/Home.module.css";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import Hero from "./components/Hero";
import TravelGuide from "./components/TravelGuide";
import AboutHero from "./components/AboutHero";
import JoinInstagram from "./components/JoinInstagram";
import RecentPosts from "./components/RecentPosts";
import SignUp from "./components/SignUp";
// import { Height } from "@material-ui/icons";

export default function Home() {
  // const classes = useStyles({});
  return (
    <div className={styles.container}>
      <Head>
        <title>KAZAMIGA | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/kazamiga.png" />
      </Head>
      <Navbar />
      <Hero />
      <TravelGuide />
      <AboutHero />
      <JoinInstagram />
      <RecentPosts />
      <SignUp />
      <Footer />
    </div>
  );
}

// const useStyles = createUseStyles({
//   container: {
//     width: 2048,
// //   },
// });
